<<<<<<< HEAD
# Generated by Django 5.0.6 on 2025-08-15 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granularity', models.CharField(choices=[('daily', '日报'), ('weekly', '周报'), ('monthly', '月报'), ('yearly', '年报'), ('custom', '自定义')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('prompt_prefs', models.TextField(blank=True, help_text='可选：额外提示，例如希望突出指标/风险等')),
                ('content_md', models.TextField(blank=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
=======
# Generated by Django 5.0.6 on 2025-08-15 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granularity', models.CharField(choices=[('daily', '日报'), ('weekly', '周报'), ('monthly', '月报'), ('yearly', '年报'), ('custom', '自定义')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('prompt_prefs', models.TextField(blank=True, help_text='可选：额外提示，例如希望突出指标/风险等')),
                ('content_md', models.TextField(blank=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]

