# Generated by Django 5.0.6 on 2025-08-19 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("deepseek", "DeepSeek"),
                            ("claude", "Claude"),
                        ],
                        max_length=20,
                    ),
                ),
                ("api_key", models.CharField(help_text="API密钥", max_length=500)),
                (
                    "api_base",
                    models.URLField(
                        blank=True,
                        help_text="API服务器地址（可选，使用默认地址则留空）",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, help_text="是否启用此配置"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("user", "provider")},
            },
        ),
    ]
