<<<<<<< HEAD
# Generated by Django 5.0.6 on 2025-08-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_worklog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workentry',
            name='end_time',
            field=models.TimeField(blank=True, help_text='结束时间', null=True),
        ),
        migrations.AddField(
            model_name='workentry',
            name='start_time',
            field=models.TimeField(blank=True, help_text='开始时间', null=True),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='本条记录的工作时长（分钟，自动计算）'),
        ),
    ]
=======
# Generated by Django 5.0.6 on 2025-08-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_worklog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workentry',
            name='end_time',
            field=models.TimeField(blank=True, help_text='结束时间', null=True),
        ),
        migrations.AddField(
            model_name='workentry',
            name='start_time',
            field=models.TimeField(blank=True, help_text='开始时间', null=True),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='本条记录的工作时长（分钟，自动计算）'),
        ),
    ]
>>>>>>> 63d039dd8c65d7691a5911951293bed90bc533ec
